### ISSUE TITLE
Add NewFile Action

### ISSUE THREAD

**Issue by timbittner** [Jooshua/e4CompareFramework-team2#33]
Similar to NewFolder Action that already exists, instead of a new folder create a new file given name and extension.

- [x] Create Handler
- [x] Create Wizard
- [x] Link in Context Menu
- [x] Create Toolbar Button

**Comment by valentinpurrucker** [comment]
- The  Context Menu item is still missing an appropriate icon for this action
- Toolbar Button is added as soon as we merge PR #35
- Filename is matches against a regex (we should take about the regex ) :D
- User gets warning if filename is not valid (not valid in the sense that the regex says it's not valid)
- if file already exits the user gets a little warning - the warning is dismissed as soon as the user focuses the textfield again, because i assume the user will focus the textfield because he/she wants to change the name.

**Comment by Jooshua** [comment]
Closed via https://github.com/TUBS-ISF/e4CompareFramework/pull/10
